import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;



        import javax.swing.*;
        import java.awt.*;
        import java.awt.event.ActionEvent;
        import java.awt.event.ActionListener;
        import java.awt.event.MouseAdapter;
        import java.awt.event.MouseEvent;

public class Test {
    private JPanel panel1;
    private JPanel zeichenflaeche;
    private JPanel steuerflaeche;
    private JButton schliessenButton;

    public Test() {
        zeichenflaeche.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                super.mousePressed(e);
                blubb(e.getX(), e.getY());
            }
        });
        schliessenButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
    }

    private void blubb(int x, int y) {
        //...
        Graphics2D g2d = (Graphics2D) zeichenflaeche.getGraphics();
        new Thread() {
            public void run() {
                try {
                    for (int i = 10; i <= 200; i += 1) {
                        g2d.setColor(Color.BLACK);
                        g2d.drawLine(x, y + i + 20, x, y + i);
                        Thread.sleep(1);
                        g2d.setColor(Color.WHITE);
                        g2d.drawLine(x, y + i + 20, x, y + i);

                    }
                } catch (
                        InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }.start();
    }


    public static void main(String[] args) {
        JFrame frame = new JFrame("Test");
        frame.setContentPane(new Test().panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        zeichenflaeche = new JPanel();
        zeichenflaeche.setLayout(new BorderLayout(0, 0));
        zeichenflaeche.setBackground(new Color(-1));
        zeichenflaeche.setEnabled(false);
        zeichenflaeche.setPreferredSize(new Dimension(800, 400));
        panel1.add(zeichenflaeche, BorderLayout.CENTER);
        steuerflaeche = new JPanel();
        steuerflaeche.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(steuerflaeche, BorderLayout.SOUTH);
        schliessenButton = new JButton();
        schliessenButton.setText("Schliessen");
        steuerflaeche.add(schliessenButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
